
package com.heihe.crm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.crm.itheima.com/")
@XmlSeeAlso({
    
})
public interface ICustomerService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<Integer> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.heihe.crm.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTeltphone", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindCustomerByTeltphone")
    @ResponseWrapper(localName = "findCustomerByTeltphoneResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindCustomerByTeltphoneResponse")
    public Customer findCustomerByTeltphone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidezoneByCustomerAdress", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindDecidezoneByCustomerAdress")
    @ResponseWrapper(localName = "findDecidezoneByCustomerAdressResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindDecidezoneByCustomerAdressResponse")
    public String findDecidezoneByCustomerAdress(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.heihe.crm.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @return
     *     returns java.util.List<com.heihe.crm.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListNotAsscoiation", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindListNotAsscoiation")
    @ResponseWrapper(localName = "findListNotAsscoiationResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindListNotAsscoiationResponse")
    public List<Customer> findListNotAsscoiation();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.heihe.crm.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListAsscoiation", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindListAsscoiation")
    @ResponseWrapper(localName = "findListAsscoiationResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.heihe.crm.FindListAsscoiationResponse")
    public List<Customer> findListAsscoiation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
